---
collections:
  - name: infra.aap_configuration
    version: "1.0.0"
  - name: infra.ee_utilities
  - name: infra.aap_utilities
  - name: containers.podman
  - name: ansible.platform
  - name: ansible.hub
  - name: ansible.controller
  - name: ansible.eda
...
