---
collections:
  - name: infra.aap_configuration
    version: "3.5.0"
  - name: infra.ee_utilities
    version: "4.0.4"
  - name: infra.aap_utilities
    version: "2.8.0"
  - name: containers.podman
    version: "1.18.0"
  - name: ansible.platform
  - name: ansible.hub
  - name: ansible.controller
  - name: ansible.eda
  
...
