---
controller_inventories_networkteam:
  - name: config_as_code_networkteam
    description: inventory for configuring as code
    organization: networkteam
aap_organizations_networkteam:
  - name: networkteam
    galaxy_credentials:
      - hub_published
      - hub_certified
      - hub_validated
      - hub_community
  # default_environment: supported
controller_credentials_networkteam:
  - name: aap_networkteam
    credential_type: Red Hat Ansible Automation Platform
    organization: networkteam
    description: aap org admin account for networkteam
    inputs:
      host: "{{ aap_hostname }}"
      username: config_as_code_networkteam
      password: "{{ aap_password }}"
      verify_ssl: false
aap_user_accounts_networkteam:
  - username: networkteam_org_admin_service_account
    is_superuser: false
    password: "{{ aap_password }}"
gateway_role_user_assignments_networkteam:
  - role_definition: Organization Admin
    user: networkteam_org_admin_service_account
    object_ids: networkteam
controller_templates_networkteam:
  - name: aap_config_networkteam
    project: config_as_code_networkteam
    job_type: run
    playbook: playbooks/aap_config.yml
    inventory: config_as_code_networkteam
    execution_environment: Default execution environment
    concurrent_jobs_enabled: false
    ask_variables_on_launch: true
    limit: "{{ env }}"
    verbosity: 0
    credentials:
      - aap_networkteam
      - vault
controller_projects_networkteam:
  - name: config_as_code_networkteam
    description: config as code project
    organization: networkteam
    scm_type: git
    scm_url: git@github.com:djdanielsson/casc_demo_2.git # will need a repo prior to put into code
    scm_branch: "{{ scm_branch }}"
    scm_clean: true
    scm_update_on_launch: false
    scm_credential: "github" # will need a cred prior to pull their repo
    update_project: true
    wait: true

...
