---
# ansible-config-as-code/playbooks/project.yml
- name: Create Projects in Ansible Automation Platform
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create or update each project
      ansible.controller.project:
        name: "{{ item.name }}"
        organization: "{{ item.organization }}"
        scm_url: "{{ item.scm_url }}"
        scm_branch: "{{ item.scm_branch }}"
        scm_type: "{{ item.scm_type }}"
        scm_clean: "{{ item.scm_clean }}"
        scm_delete_on_update: "{{ item.scm_delete_on_update }}"
        credential: "{{ item.credential }}"
        state: present
      loop: "{{ projects_to_create }}"
