---
# ansible-config-as-code/playbooks/project.yml
- name: Create Projects in Ansible Automation Platform
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Debugging the varnames lookup
      ansible.builtin.debug:
        msg: "{{ lookup('ansible.builtin.varnames', 'controller_projects_all') }}"
    - name: Set fact for controller_projects
      ansible.builtin.set_fact:
        controller_projects: "{{ (controller_projects | default([])) + lookup('ansible.builtin.vars', item) }}"
      loop: "{{ [] if (lookup('ansible.builtin.varnames', 'controller_projects.*')) is not string else (lookup('ansible.builtin.varnames', 'controller_projects.*') | split(',')) }}"

